import Head from "next/head";
import {
  Input,
  Spacer,
  Textarea,
  Button,
  Container,
  Row,
  Text,
} from "@nextui-org/react";
import Comment from "../components/comment";

export default function Home(props) {
  const { comments } = props;
  console.log("Comments: ");
  console.log(comments);
  return (
    <>
      <Head>
        <title>JAMMA Comments</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container gap={1} fluid css={{ fontFamily: "Roboto" }}>
        <Spacer y={1} />
        <Row fluid>
          <Input
            labelLeft="Username"
            placeholder="lonewanderer27"
            bordered={false}
            fullWidth
          />
        </Row>
        <Spacer y={0.5} />
        <Row>
          <Input
            labelLeft="Email"
            placeholder="user@mail.com"
            bordered={false}
            fullWidth
          />
        </Row>
        <Spacer y={0.5} />
        <Row>
          <Input
            labelLeft="Phone"
            placeholder="+639983082814"
            bordered={false}
            fullWidth
          />
        </Row>
        <Spacer y={0.5} />
        <Row>
          <Textarea
            placeholder="Write your thoughts"
            bordered={false}
            fullWidth
          />
        </Row>
        <Spacer y={0.5} />
        <Row fluid justify="flex-end">
          <Button color="gradient" size="sm">
            Submit
          </Button>
        </Row>
      </Container>
      <Container gap={1} fluid css={{ fontFamily: "Roboto" }}>
        <Spacer y={1} />
        <Text h3>{Object.keys(comments).length} Responses:</Text>
        {Object.entries(comments).map((value) => {
          const key = value[0];
          const data = value[1];

          return (
            <>
              <Row key={"r" + key}>
                <Comment key={"c" + key} data={data} />
              </Row>
              <Spacer y={1} />
            </>
          );
        })}
      </Container>
    </>
  );
}

export async function getServerSideProps() {
  const admin = require("firebase-admin");
  const serviceAccount = require("../serviceAccountKey.json");

  if (!admin.apps.length) {
    admin.initializeApp({
      credential: admin.credential.cert(serviceAccount),
      databaseURL:
        "https://jamma-comments-332612-default-rtdb.asia-southeast1.firebasedatabase.app",
    });
  }

  const db = admin.database();
  const ref = db.ref("messages");
  let entries = {};
  const response = await ref.once("value", (snapshot) => {
    entries = snapshot.val();
  });

  console.log("response");
  console.log(response);

  console.log("comments");
  console.log(entries);

  return {
    props: {
      comments: entries,
    },
  };
}
